- name: download archive files
  get_url:
    url: "https://github.com/{{ item.repo }}/releases/download/{{ item.version }}/{{ item.file }}"
    dest: /tmp
  with_items:
    - "{{ packages }}"
  register: download_files

- name: unarchive binaries
  unarchive:
    remote_src: yes
    src: "{{ item.dest }}"
    dest: /tmp
  with_items:
    - "{{ download_files.results }}"
  register: unarchive_files

- name: move binaries to /usr/local/bin
  copy:
    src: "/tmp/{{ item.item.item.binary }}"
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  with_items:
    - "{{ unarchive_files.results }}"
  become: yes
